name: artifact

on: [push]

env:
  FILE_NAME: hello-server


jobs:
  build:
    name: Build
    runs-on: ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
        run: go build ${{ env.FILE_NAME }}.go
      
      - name: List files 
        run: ls -ltr

      - name: Upload artifact for linux
        uses: actions/upload-artifact@v4.3.4
        with:
          name: linux
          path: ./${{ env.FILENAME }}
  test-linux:
    name: TEst Linux
    runs-on: [ubuntu-latest]
    needs: [build]
    steps:

      - name: checkout code
        uses: actions/checkout@v4
      
      - name: List files 
        run: ls -ltr
      
      - name: Download artfact
        uses: actions/download-artifact@4.1.8
        with:
          name: linux
      
      - name: List files 
        run: ls -ltr
      
      - name: test ${{ env.FILE_NAME }}
        run: source ./test.sh

